replicaCount: 1

image:
  repository: josephmuli/demo-server
  pullPolicy: IfNotPresent
  tag: "1.0.1-dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP
  port: 3030

k8s-as-helm:
  configmapData:
    SERVER_USERNAME: "development"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
