replicaCount: 1

image:
  repository: josephmuli/demo-server
  pullPolicy: IfNotPresent
  tag: "1.0.1-dev"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

config:
  ConfigMap: demo-config


service:
  type: ClusterIP
  port: 3030

# Create a configmap with environment-specific config.
k8s-as-helm:
  name: demo-config
  configmapData:
    SERVER_USERNAME: "development"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
