apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: blue-developer-role-binding
  namespace: production
roleRef:
  kind: Role
  name: blue-production-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io