
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: blue-development-role
  namespace: development
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]