apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-team-cluster-role-binding
  namespace: development
roleRef:
  kind: ClusterRole
  name: platform-team-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: administrator
  apiGroup: rbac.authorization.k8s.io